---
title: "Final_Report_Markdown"
author: "Samuel Chase,Kirsten Mork, Andrew Rose"
date: "December 11, 2016"
output: html_document
---
<h3>College Scorecard Shiny App</h3>

<p>Our shiny application uses College ScoreCard Data and visualizes linear regressions of various variables in the massive data set.  The data was gathered by US Department of Education and contains information concerning colleges' locations, size, students, costs, and more.  However, the dataset is fairly large with over 7700 schools entered and over 70 columns.  This is a lot of data to sift through, so our app is an effective way to easily see trends and summaries of some of the more crucial information.</p>

<h3>Our Goal</h3>

<p>Searching for a college can be hard. There are lots of factors - what region do I want to live in? Is private better than public? What is the average SAT score of my favorite school?</p>

<p>We wanted to provide tools users to answer some of these questions. By allowing users to select between certain factors (ie location) we allow users to analyze schools based on specific factors. The plots allow users to see overall trends of universities in the specific factor set they wish, whereas the data table and plotly selection feature allow them to zoom in on specific schools to see more. We wanted to allow students to intelligently and easily run queries and gather stastics about schools - both nationwide and in whatever subcategories they wished. </p>

<p>Our tool has a X/Y plot to show bivariate data. We offer regression lines and confidence intervals to provide baselines and estimate relationships between variables. We offer prediciton intervals to predict individual values. We also have a histogram to analyze univariate data, and a data table to show all the schools in our data set.</p>

<h3>How to use the App</h3>

<p>Our app offers many filtering options for our data. The check boxes above the X/Y selections offer the ability to sort your colleges by region, and whether or not the school is public, private, or private for profit. These are all checked by default but can be paired down to the user's liking. This affects both the Data Table and the Plotly plot of variables.</p>

<p>The X/Y selection box offers the user a mulitude of options to plot via plotly. This data can then be analyzed point by point by hovering over the graph, or by the use of regression lines, confidence intervals, and prediction intervals. Below that is the univariate histogram variable selector.</p>

<p>To the right of the data input is the plotly graph itself, which features a plot of the selected X and Y variables. Below the plotly x/y graph is a univariate histogram of a single variable. Under that is the datatable (created by DT) which shows information about all selected colleges. It includes a search bar so that one can prepare basic queries for the data table.</p>

<h3>Plotting with the College Scorecard App</h3>

<p>Using the X and Y selection boxes, users can choose which variables to display on a scatterplot. Selection box options also allows users to turn regression information on or off, and narrow down the data based on different selection criteria. Scatterplots are rendered using Plotly, an R package used for making interactive graphs. And example graphic that could be shown in this app is shown below.</p>

```{R echo = F, message = F}
library(magrittr)
library(plotly)

score <- read.csv("data/Most-Recent-Cohorts-All-Data-Elements.csv", as.is = T)
score <- score[,c("INSTNM", "STABBR", "REGION", "LATITUDE", "LONGITUDE", "CONTROL", "SAT_AVG_ALL", "ACTCMMID", "UGDS", "NPT4_PUB", "NPT4_PRIV", "MN_EARN_WNE_P10", "PCTFLOAN", "ADM_RATE_ALL")]
colnames(score) <- c("College Name", "State", "Region", "Latitude", "Longitude", "Control", "AverageSAT", "AverageACT", "NumberofStudents", "PublicNetCost", "PrivateNetCost", "MeanEarnings", "PercentFedLoan", "AdmissionRate")
score[score$Latitude == "NULL", "Latitude"] <- NA
score[score$Longitude == "NULL", "Longitude"] <- NA
score$Latitude <- as.numeric(score$Latitude)
score$Longitude <- as.numeric(score$Longitude)
  
score[score$AverageACT == "NULL", "AverageACT"] <- NA
score[score$AverageSAT == "NULL", "AverageSAT"] <- NA
score$AverageACT <- as.numeric(score$AverageACT)
score$AverageSAT <- as.numeric(score$AverageSAT)
  
plotData <- score[!is.na(score[, "AverageACT"]) & !is.na(score[, "AverageSAT"]), ]
    
model <- lm(AverageACT ~ AverageSAT, data = plotData)
predictObj <- predict(model, interval = "prediction", level = 0.99)
confObj <- predict(model, interval = "confidence", level = 0.99)

plot <- plot_ly(plotData, x = ~AverageSAT) %>% add_markers(y = ~AverageACT, name = "", text = plotData[,"College Name"], showlegend = F)

plot <- add_ribbons(plot, ymin = ~predictObj[,"lwr"], ymax = ~predictObj[,"upr"], line = list(color = 'rgba(255, 246, 79, 0.4)'), fillcolor = 'rgba(255, 246, 79, 0.4)', name = "99% Prediction Interval")
plot <- add_ribbons(plot, ymin = ~confObj[,"lwr"], ymax = ~confObj[,"upr"], line = list(color = 'rgba(255, 150, 0, 0.4)'), fillcolor = 'rgba(255, 204, 0, 0.4)', name = "99% Confidence Interval")

plot <- add_lines(plot, y = ~fitted(model), line = list(color = "red"), name = "Regression Line")

plot
```

